# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'macaw_practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "Macaw", "0.9.7"

  # Pods for macaw_practice

end
